import 'dotenv/config'

import cors from '@fastify/cors'
import jwt from '@fastify/jwt'
import fastify from 'fastify'

import AuthRoutes from './routes/auth'
import postsRoutes from './routes/posts'

const app = fastify()
const port = 3333

app.listen({ port }).then(() => {
  console.log(`Server listening on port http://localhost:${port}`)
})

// CORS settings: every fron-end url request has access
app.register(cors, {
  origin: true,
})

// secret is a way to diff "jwt generated by this backent" by "others jwt of others backends" (it's like a cryptograph)
app.register(jwt, {
  secret: 'soyoulikekissingboysdontyou',
})

app.register(postsRoutes)
app.register(AuthRoutes)
